6pin n64 Joystick option
sfraint/wireless-n64-controller pull request #9
Opened 2023-03-06 23:50 UTC by craigmillard86

Adding OEM n64 Joystick including calibration

2023-03-12 22:04 UTC, sfraint requested changes
Very cool! 😎 thanks @craigmillard86!

I left several smaller comments in-line.

----

I assume you were able to get this to work with your controller and joystick for both X axis and Y axis? I couldn't make it work with my 6-pin joystick - only the Y axis works for me for some reason.

2023-03-31 22:12 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +    xQueueSendFromISR(gpio_sixpin_queue, &gpio_num, NULL);
Yep, no longer required, removed.

2023-03-31 22:12 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +static void gpio_task_sixpin(void* arg)
Yep, no longer required, removed.

2023-03-31 22:12 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +        //enable pull-up mode
Yep, updated all comments in this section

2023-03-31 22:15 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +uint16_t absolute_value(int32_t value) {
This function converts the min value from a negative to a positive number. Name and comments updated

 The factor_* is then used to move the centre and max values up in relation to the updated min.

2023-03-31 22:15 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +    mn_x = (mn_x /2)*2;
comment added

2023-03-31 22:16 UTC, craigmillard86 commented on software/main/input_poll.h
> +#define ANALOG_MAX        130
This has been updated, only the SIXPIN_Enabled define requires a change to enable.

2023-03-31 22:16 UTC, craigmillard86 commented on software/main/storage.cpp
> +        printf("Failed to write %s\n", name3);
correct, updated

2023-03-31 22:17 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +        io_conf.intr_type = GPIO_INTR_ANYEDGE;
yep comment has been updated.

2023-03-31 22:18 UTC, craigmillard86 commented on software/main/input_poll.h
> +#define SIXPIN_ENABLED  1
Missed that, thought i had set before committing :)

2023-03-31 22:19 UTC, craigmillard86 commented on software/main/input_poll.h
> +#define SIXPIN_ANALOG_XQ             35
Thats correct, I couldn't see another free PIN and as this is using the external Battery board on the rumble pack I didn't think this was needed?

2023-03-31 22:21 UTC, craigmillard86 commented
> Very cool! 😎 thanks @craigmillard86!
> 
> I left several smaller comments in-line.
> 
> I assume you were able to get this to work with your controller and joystick for both X axis and Y axis? I couldn't make it work with my 6-pin joystick - only the Y axis works for me for some reason.

Thanks @sfraint, mostly there now I think:)

Yeah I have this working on 2 different controllers at the moment Green and Red originals. Have 2 Greys to do next! Works great, thanks for the project!!

2023-04-01 20:18 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
> +uint16_t absolute_value(int32_t value) {
I should have been more specific here. The part that doesn't line up with the function name / comment is

```
    } else {
        return 0;
    }
```

This makes the function not just remove the negative part, it zeros out any positive input. i.e. it would end up doing:
`convert_positive(-10)` -> `10`
`convert_positive(10)` -> `0`

When just looking at the function name and comment, I would assume it would be `...(-10)` -> `10` but also `...(10)` -> `10`

2023-04-01 20:40 UTC, sfraint requested changes
Yeah, it's looking close! just a couple more comments.

I'll try to set aside some time next week to test this out again, but unfortunately I don't think I have the right hardware to do _real_ 6-pin testing.

2023-04-01 20:40 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
>      adc1_config_channel_atten(ANALOG_BAT, ADC_ATTEN_DB_11);
Can you skip ADC configuration for the battery pin (and also not attempt to read the battery voltage) if that pin is being used for 6-pin?

2023-04-01 20:40 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
> +        factor_x = 40;
>        factor_x = 40;
>        factor_y = 40;

I'd still like to see if `factor_x` and `factor_y` can be completely removed.

I think if you assume `center_x` and `center_y` are both always `0`, then you just need to determine the `min_*` and `max_*` values and don't need `factor_*` at all.

2023-04-02 08:22 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
>      adc1_config_channel_atten(ANALOG_BAT, ADC_ATTEN_DB_11);
Yeah missed that, have updated it to depend on SIXPIN_Enabled as well as the actual check

2023-04-02 08:34 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +uint16_t absolute_value(int32_t value) {
OK i get what you mean now:) I didn't want to include an additional library just to use abs but it's already included and I didn't notice. I switched to using abs() instead! Also, no idea why I was returning 0 should have been value!

2023-04-02 09:14 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +        factor_x = 40;
the factor_* is used within the interrupt handler to shift the count* to the correct range. If this handler takes too long to process then it blocks the application and causes the esp32 to reboot. 
I could switch to using abs(min_*) here and elsewhere but I wanted to avoid adding the additional processing in the handler, hence the Var and then it's just an addition in the handler.

The Queues I had originally in the code were first stab at processing the count*'s but the queue operations were too slow for the joystick movements, hence completing it in the handler directly.

2023-04-02 09:28 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +        factor_x = 40;
the factor is used to adjust the whole range of the 6pin joystick into positive. e.g.
Raw output:
min = -41
center = 0
max = 41
the factor is then the absolute of the min so the resulting absolute joystick range is:
min = 0
center = 41
max = 82
once the factor is calculated (via calibration or preset 40) it is then needed to adjust the count* throughout the code. 
Because each Joystick min values depends on the wear of the stick this is likely to be different for each joystick and I can't see a way to calculate the minimum outside of calibration to detect the maximum range of the joystick?

2023-04-02 20:54 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
> +        factor_x = 40;
That all makes sense, but I don't think you need a separate variable for `factor` (and don't need to write to non-volatile storage).

I think you can just:
1. leave min `-41`, center `0`, and max `41`
2. in `get_sixpin_count`, just return `countx - min_x`
3. similarly scale the `min`, `center`, and `max` values passed in to `analog_to_joystick_value`.

----

If you do that, I think you can completely remove the `factor` variables, keep the old non-volatile storage code,

2023-04-26 12:07 UTC, craigmillard86 commented
That makes sense, it took me a while!

I have updated to resolve this, to be able to achieve it the mix/max/center etc needed to change from unit to int as for SIXPIN we are dealing with negative values, I don't think this will impact the 4pin version from what I can see.

2023-04-26 12:08 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +        factor_x = 40;
Updated to resolve

2023-04-30 20:29 UTC, craigmillard86 commented
> Yeah, it's looking close! just a couple more comments.
> 
> I'll try to set aside some time next week to test this out again, but unfortunately I don't think I have the right hardware to do _real_ 6-pin testing.

2023-04-30 21:59 UTC, sfraint requested changes
Awesome, thanks @craigmillard86!

Unfortunately, I haven't had a chance to test this out yet. I left a few small comments related to the cleanup - I'll try to get around to testing this after you make these last few changes.

2023-04-30 21:59 UTC, sfraint commented on building.md
> +input_poll.h - #define SIXPIN_ENABLED  1
nit: can you use `code format` here for clarity, e.g.
> In input_poll.h - `#define SIXPIN_ENABLED  1`

2023-04-30 21:59 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
> +// When an edge change is detected used to count movement
>// When an edge change is detected used to count movement

Can you tweak this comment to include the fact that this is specific to 6-pin joysticks?
e.g.

>// For 6-pin joysticks: count movement when an edge change is detected

2023-04-30 21:59 UTC, sfraint commented on software/main/input_poll.cpp
> +    currentXState = analog_to_joystick_value(get_sixpin_count(0), min_x+abs(min_x), center_x+abs(min_x), max_x+abs(min_x));
Can you just use `countx+abs(min_x)` instead of `get_sixpin_count(0)`? It's a little clearer what is going on if you do that

2023-04-30 21:59 UTC, sfraint commented on software/main/input_poll.cpp
> +    currentYState = analog_to_joystick_value(get_sixpin_count(1), min_y+abs(min_y), center_y+abs(min_y), max_y+abs(min_y));;
Similar comment here, `county+abs(min_y)` instead of `get_sixpin_count(1)`

2023-04-30 21:59 UTC, sfraint commented on software/main/storage.h
> +bool write_storage_values(char* name1, uint32_t value1, char* name2, uint32_t value2, char* name3, uint32_t value3, char* name4, uint32_t value4);
I don't think `write_storage_values` takes in a 4th value anymore - should just remove this from the function declaration here.

2023-04-30 21:59 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
> +// Setup Var to hold Factor to move joystick to positive range
>// Setup Var to hold Factor to move joystick to positive range
>uint16_t factor_x = 0;
>uint16_t factor_y = 0;

You should be able to remove these `factor_*` variables now (and there references below)

2023-04-30 21:59 UTC, sfraint commented on software/main/ble_gamepad_main.h
> +#define STORAGE_KEY_Y_FACTOR   "factor_y"
>#define STORAGE_KEY_X_FACTOR   "factor_x"
>#define STORAGE_KEY_Y_FACTOR   "factor_y"

You can remove these too

2023-04-30 21:59 UTC, sfraint commented on software/main/ble_gamepad_main.cpp
> +uint16_t get_sixpin_count(int32_t type) {
I'd say just remove this function and in-line `countx+abs(min_x)` and `county+abs(min_y)` where those are used.

2023-05-01 08:31 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +// When an edge change is detected used to count movement
Updated, also went through the rest and updated to similar format

2023-05-01 08:31 UTC, craigmillard86 commented on software/main/input_poll.cpp
> +    currentXState = analog_to_joystick_value(get_sixpin_count(0), min_x+abs(min_x), center_x+abs(min_x), max_x+abs(min_x));
Updated, changed location of def to allow access from both classes

2023-05-01 08:32 UTC, craigmillard86 commented on software/main/storage.h
> +bool write_storage_values(char* name1, uint32_t value1, char* name2, uint32_t value2, char* name3, uint32_t value3, char* name4, uint32_t value4);
Looks like i missed this file in my commit! updated now

2023-05-01 08:32 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +// Setup Var to hold Factor to move joystick to positive range
Removed, also removed 2nd location which had been missed.

2023-05-01 08:33 UTC, craigmillard86 commented on software/main/ble_gamepad_main.h
> +#define STORAGE_KEY_Y_FACTOR   "factor_y"
removed

2023-05-01 08:33 UTC, craigmillard86 commented on software/main/ble_gamepad_main.cpp
> +uint16_t get_sixpin_count(int32_t type) {
No longer required as highlighted, removed

2023-05-01 08:33 UTC, craigmillard86 commented on software/main/input_poll.cpp
> +    currentYState = analog_to_joystick_value(get_sixpin_count(1), min_y+abs(min_y), center_y+abs(min_y), max_y+abs(min_y));;
Updated.

2023-05-01 08:36 UTC, craigmillard86 commented on building.md
> +input_poll.h - #define SIXPIN_ENABLED  1
Updated.

2023-05-01 08:37 UTC, craigmillard86 commented
> Awesome, thanks @craigmillard86!
> 
> Unfortunately, I haven't had a chance to test this out yet. I left a few small comments related to the cleanup - I'll try to get around to testing this after you make these last few changes.

Changes made, let me know if you spot anything else and how the testing goes!

2023-05-21 21:55 UTC, sfraint requested changes
I finally got a chance to test it out. I still don't have a real 6-pin joystick to try, but from what I was able to test it seems great!

I left one final requested change: reset that `SIXPIN_ENABLED` define back to `0` - after that, we can merge this PR.

Thanks again @craigmillard86!

2023-05-21 21:55 UTC, sfraint commented on software/main/input_poll.h
> +#define SIXPIN_ENABLED  1
Looks like this was changed back to `1` - I think this is the last change before we can merge it!

2023-05-27 16:32 UTC, craigmillard86 commented
> I finally got a chance to test it out. I still don't have a real 6-pin joystick to try, but from what I was able to test it seems great!
> 
> I left one final requested change: reset that `SIXPIN_ENABLED` define back to `0` - after that, we can merge this PR.
> 
> Thanks again @craigmillard86!

Thats great! I have updated and committed:)

Works well on my 4 controllers.

2023-05-28 20:37 UTC, sfraint approved these changes
Awesome, thanks for the contribution @craigmillard86!

2023-05-28 20:38 UTC, merged